# Devotions - Deities and Blessings
# Made by xIdentified - https://discord.gg/yRrbBjfbXp

initial-favor: 50 # Favor players start out with
max-favor: 250 # Max amount of favor players can have
decay-rate: 5 # Rate at which favor decays over time
decay-interval: 1200 # How often favor decays (in seconds) 1200 = 1 day

# Amount of favor player should have for certain actions to occur
blessing-threshold: 150
curse-threshold: 35
miracle-threshold: 210

# Chances for certain events to occur once a player is above threshold
blessing-chance: 0.4 #0.5 = 50%, 0.05 = 5% chance of occurring once per effect-interval
curse-chance: 0.1
miracle-chance: 0.03
days-until-miracles-start: 3 # How many days should a player maintain their high favor before miracles start occurring?
effect-interval: 1800 # How often to check if player has blessing/curse/miracle available (in seconds)

# Cooldowns (format can be 5s / 5m / 5h)
offering-cooldown: "5m"
ritual-cooldown: "5m"
blessing-cooldown: "5m"
curse-cooldown: "5m"
miracle-cooldown: "5m"

# How many shrines can a player have at once?
shrine-limit: 3

debug_mode: false